# steps:
#   - name: 'hashicorp/terraform:1.0.0'
#     entrypoint: 'sh'
#     args:
#     - '-c'
#     - |
#       terraform version
#       terraform init -input=false -no-color
#       terraform validate -no-color
#       if [ "$BRANCH_NAME" = "dev" ]; then
#         terraform plan -input=false -no-color -out=tfplan
#       elif [ "$BRANCH_NAME" = "main" ]; then
#         terraform plan -input=false -no-color -out=tfplan
#         terraform apply -auto-approve -no-color tfplan
#       else
#         echo "Not a dev or main branch. Skipping Terraform operations."
#       fi
# artifacts:
#   objects:
#     location: 'gs://${PROJECT_ID}-terraform-state/cloudbuild-artifacts/'
#     paths: ['tfplan']
# timeout: '1800s'
# options:
#   logging: CLOUD_LOGGING_ONLY


steps:
  - name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'sh'
    args:
    - '-c'
    - |
      echo "Current branch: $BRANCH_NAME"
      terraform version
      terraform init -input=false -no-color
      terraform validate -no-color
      if [ "$BRANCH_NAME" = "dev" ]; then
        echo "Running plan for dev branch"
        terraform plan -input=false -no-color -out=tfplan
      elif [ "$BRANCH_NAME" = "main" ]; then
        echo "Running plan and apply for main branch"
        terraform plan -input=false -no-color -out=tfplan
        terraform apply -auto-approve -no-color tfplan
      else
        echo "Not a dev or main branch. Skipping Terraform operations."
      fi